name: Release

# Only run this workflow on pushed tags.
on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  check-version:
    name: Check ered application version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Install Erlang/OTP
        uses: erlef/setup-beam@3580539ceec3dc05b0ed51e9e10b08eb7a7c2bb4 # v1.21.0
        with:
          otp-version: '28.1.1'
          rebar3-version: '3.25.1'
      - name: Check if vsn matches pushed tag (see src/ered.app.src).
        run: |
          rebar3 compile
          erl -noshell -pa _build/default/lib/*/ebin -eval "$(cat <<'EOF'
          Version = "${{ github.ref_name }}",
          application:start(ered),
          case application:get_key(ered, vsn) of
              {ok, Version} ->
                  io:format(user, "Version check ok, vsn and pushed tag is ~p~n",
                            [Version]),
                  halt(0,[]);
              Error ->
                  io:format(user, "Version check failed, got ~p while pushed tag is ~s~n",
                            [Error, Version]),
                  halt(1,[]) %% Version check failed, give exitcode 1.
          end.
          EOF
          )"
